// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtX0MVGA4id28-JBKqUCuIo1WF6x2amxo',
    appId: '1:897743036566:web:910bd7eaa45e9df97b22b7',
    messagingSenderId: '897743036566',
    projectId: 'tlpfr-93a08',
    authDomain: 'tlpfr-93a08.firebaseapp.com',
    storageBucket: 'tlpfr-93a08.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP23e4K63AFcvkWmY4kghP7UQSCmuC7IY',
    appId: '1:897743036566:android:764d41c99a20320d7b22b7',
    messagingSenderId: '897743036566',
    projectId: 'tlpfr-93a08',
    storageBucket: 'tlpfr-93a08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdPEBt0vINJPzesoeufCzQxen28bLa_ow',
    appId: '1:897743036566:ios:0721d09f85f0949e7b22b7',
    messagingSenderId: '897743036566',
    projectId: 'tlpfr-93a08',
    storageBucket: 'tlpfr-93a08.firebasestorage.app',
    iosClientId: '897743036566-4v05stf09lkhccm7vi2g6hpq1nat9fle.apps.googleusercontent.com',
    iosBundleId: 'com.tlpfr.',
  );
}
